#!/usr/bin/env python3
"""
Create GitHub issues for critical ghost CVEs.

Automatically creates issues for CVEs that have been in limbo for 30+ days.
"""

import subprocess
import sys
from datetime import datetime
from src.storage import DatabaseManager
from src.config import APP_SETTINGS


def check_issue_exists(cve_id: str) -> bool:
    """
    Check if an issue already exists for this CVE.

    Args:
        cve_id: CVE identifier

    Returns:
        True if issue exists, False otherwise
    """
    try:
        result = subprocess.run(
            ["gh", "issue", "list", "--search", f"CVE: {cve_id}", "--json", "number"],
            capture_output=True,
            text=True,
            timeout=30
        )
        return "number" in result.stdout
    except Exception as e:
        print(f"Warning: Could not check if issue exists for {cve_id}: {e}")
        return False


def create_ghost_issue(ghost, sources) -> bool:
    """
    Create a GitHub issue for a critical ghost CVE.

    Args:
        ghost: GhostCVE object
        sources: List of discovery sources

    Returns:
        True if issue created successfully
    """
    # Build issue body
    body = f"""## 🚨 Critical Ghost CVE Alert

**CVE ID**: `{ghost.cve_id}`
**Status**: {ghost.registry_status}
**First Seen**: {ghost.first_seen.strftime("%Y-%m-%d")}
**Days in Limbo**: {ghost.days_in_limbo} days
**Confidence Score**: {ghost.confidence_score:.2f}

### Discovery Sources

This CVE has been found in the following sources:

"""

    for i, source in enumerate(sources[:10], 1):
        body += f"{i}. **{source.source_name}** ({source.source_type})\n"
        body += f"   - URL: {source.evidence_url}\n"
        body += f"   - Discovered: {source.discovered_at.strftime('%Y-%m-%d')}\n"
        body += "\n"

    if len(sources) > 10:
        body += f"\n*...and {len(sources) - 10} more sources*\n"

    body += f"""

### What This Means

This CVE has been publicly mentioned for **{ghost.days_in_limbo} days** but remains:
- ❌ Not published in official NVD/MITRE registries
- ⚠️ Status: **{ghost.registry_status}**

### Possible Reasons

This could indicate:
- ✅ **Legitimate CVE** pending publication (normal processing delay)
- ⚠️ **Fake/Test CVE ID** (spam or demo data)
- 🔄 **Published under different ID** (CVE ID reassignment)
- 📝 **Documentation error** in source materials

### Action Items

- [ ] Verify CVE legitimacy by checking all sources
- [ ] Search NVD/MITRE for similar vulnerabilities
- [ ] Contact CVE authorities if needed
- [ ] Update blacklist in `src/config.py` if confirmed fake
- [ ] Close this issue when resolved

### Monitoring

This issue was auto-generated by Ghost Hunter and will be monitored:
- ✅ Auto-close if CVE gets published
- ⚠️ Escalate if CVE reaches 60+ days
- 📊 Update if new sources discovered

### Resources

- [NVD Search](https://nvd.nist.gov/vuln/search/results?form_type=Basic&results_type=overview&query={ghost.cve_id})
- [MITRE Search](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword={ghost.cve_id})
- [View Dashboard](https://rogolabs.github.io/GhostCVEs)

---
*Auto-generated by Ghost Hunter on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}*
"""

    try:
        # Create the issue
        result = subprocess.run(
            [
                "gh", "issue", "create",
                "--title", f"🚨 Critical Ghost: {ghost.cve_id} ({ghost.days_in_limbo} days)",
                "--body", body,
                "--label", "critical-ghost,automated"
            ],
            capture_output=True,
            text=True,
            timeout=60
        )

        if result.returncode == 0:
            print(f"✓ Created issue for {ghost.cve_id}")
            return True
        else:
            print(f"✗ Failed to create issue for {ghost.cve_id}: {result.stderr}")
            return False

    except Exception as e:
        print(f"✗ Error creating issue for {ghost.cve_id}: {e}")
        return False


def main():
    """Main entry point."""
    print("🔍 Checking for critical ghost CVEs...")

    # Initialize database
    db = DatabaseManager()

    # Get all ghost CVEs
    ghosts = db.get_ghost_cves(only_ghosts=True)

    # Filter to critical (30+ days)
    critical_ghosts = [
        g for g in ghosts
        if g.days_in_limbo >= APP_SETTINGS.limbo_critical_days
    ]

    if not critical_ghosts:
        print("✓ No critical ghosts found (all under 30 days)")
        return 0

    print(f"Found {len(critical_ghosts)} critical ghost(s)")

    created = 0
    skipped = 0

    for ghost in critical_ghosts:
        # Check if issue already exists
        if check_issue_exists(ghost.cve_id):
            print(f"⏭️  Skipping {ghost.cve_id} (issue already exists)")
            skipped += 1
            continue

        # Get sources for this CVE
        sources = db.get_sources_for_cve(ghost.cve_id)

        if not sources:
            print(f"⚠️  Skipping {ghost.cve_id} (no sources found)")
            continue

        # Create the issue
        if create_ghost_issue(ghost, sources):
            created += 1

    print(f"\n📊 Summary:")
    print(f"  - Critical ghosts: {len(critical_ghosts)}")
    print(f"  - Issues created: {created}")
    print(f"  - Issues skipped: {skipped}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
